### ISSUE TITLE
7장 check 패키지 다운로드

### ISSUE THREAD

**Issue by KimBoWoon** [DiscoverMeteor/DiscoverMeteor_Kr#62]
meteor를 열심히 공부하는 학생입니다.
7장을 보면서 공부하는중인데 실행시키니까 Server Error가 나와서 GitHub코드를 보다보니까 check 패키지를 사용했습니다.
반면에 책에서는 check 패키지를 받으라는 설명이 없어서 한참을 헤맸습니다
저처럼 헤매는 사람이 없길바라면서 issues를 남깁니다

**Comment by miraten** [comment]
현재 DiscoverMeteor 책은 예전 1.0 버전 또는 그 이하 버전을 대상으로 한 내용이구요. 이후 원서가 업데이트 되고 있지만, 번역서는 계속 이를 따라가지 못하고 있습니다. 
예전에는 check 패키지가 core 패키지에 기본 포함되어 있었는데... 업그레이드 되면서 빠지게 되었어요. 그래서 발생한 문제인 듯 합니다.

Meteor를 공부하시려면, 이 번역본은 참고 정도로 생각하시고, 원본을 보시거나 다른 소스를 참고하시기 바랍니다.

**Comment by KimBoWoon** [comment]
아 그렇군요
답변 감사합니다
